[build]
target = "riscv64imac-unknown-none-elf"

[target.riscv64imac-unknown-none-elf]
runner = [
    "qemu-system-riscv64",
    "-machine", "virt",
    "-cpu", "rv64",
    "-d", "guest_errors,unimp",
    "-smp", "1",
    "-m", "128M",
    "-serial", "mon:stdio",
    "-nographic",
    "-append", "loglevel=trace",
    # "-device", "virtio-rng-device",
    # "-device", "virtio-gpu-device",
    # "-device", "virtio-net-device",
    # "-device", "virtio-tablet-device",
    # "-device", "virtio-keyboard-device",
    # "-s", "-S",
    "-kernel"
]
rustflags = ["-C", "link-arg=-Tsrc/linker/qemu-virt.lds"]

[unstable]
build-std = ["core", "compiler_builtins"]
